export default {
    products: [
        {
            _id: '1',
            name: 'Sunset Jump',
            category: 'options',
            image: '/images/sunset.jpg',
            price: 200,
            brand: 'Poop',
            rating: 5,
            numReviews: 10,
            description: 'Jump conducted 15 minutes before sunset',
        },
        {
            _id: '2',
            name: 'Additional Jumpers',
            category: 'options',
            image: '/images/metal.jpg',
            price: 80,
            brand: 'Icarus',
            rating: 5,
            numReviews: 5,
            description: 'Maximum four jumpers and one',
        },
        {
            _id: '3',
            name: 'Smoke Trails',
            category: 'options',
            image: '/images/pipe.jpg',
            price: 100,
            brand: 'NZ Aerosports',
            rating: 5,
            numReviews: 12,
        },
        {
            _id: '4',
            name: 'Wave',
            category: 'options',
            image: '/images/wave.jpg',
            price: 190,
            brand: 'Fluid Wings',
            rating: 2.8,
            numReviews: 4,
        },
    ],
};
